[profile.default]
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
